SET session_replication_role = replica;

--
-- PostgreSQL database dump
--

-- \restrict 6n0tB16XCYaWPkmdk0GPEb6Ni3DABEZC9hqIcrVjCsJGCfwZccvHGKSamU0mtgs

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: cards; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "public"."cards" ("id", "num", "title", "difficulty", "tags", "key_points", "complexity", "follow_ups", "gotchas", "created_at", "last_reviewed", "description", "example", "stumbles", "completion_count") VALUES
	(28, 560, 'Subarray Sum Equals K', 'medium', '{array,hash-table,prefix-sum}', '["Prefix sum + HashMap：對每個 prefix_sum 查 prefix_sum - k 在 map 裡幾次", "seen = {0: 1} 初始化 — 讓從頭開始的 subarray 也能配對", "HashMap 存「次數」不是 True/False — 同 prefix_sum 會重複出現", "先 count += seen.get(prefix_sum - k, 0) 再登記自己進 map", "結構跟 Two Sum 一致：查 complement → 登記自己"]', 'O(n) time, O(n) space', '["能用 sliding window 嗎？— 不行，nums 可能有負數，sum 不單調", "如果要回傳起訖 index？— seen 存 index 而非次數，subarray = nums[seen_index+1 : i+1]", "同模式變體 — https://leetcode.com/problems/subarray-sums-divisible-by-k/"]', '["忘記 seen = {0: 1} — 從頭開始、總和剛好 k 的 subarray 會漏掉", "存 True/False 而非 count — 有負數時同 prefix_sum 重複出現會少算", "Brute force sum(nums[i:j]) 是 O(n³) 不是 O(n²) — 每次 sum 又是 O(n)"]', '2026-04-16 11:53:02.007811+00', '2026-05-10 15:13:52.513+00', 'Given an array of integers nums and an integer k, return the total number of contiguous subarrays whose sum equals k.', 'Input: nums = [1,2,3], k = 3
Output: 2', '["sum_counts[x]=2 是兩個合法起點 candidates，不是 double-count — 加進 map 不是加進 count", "Map entry 不會被『用掉』— 同個起點可配多個未來終點，每對都算一個合法 subarray"]', 2),
	(24, 706, 'Design HashMap', 'easy', '{hash-table,design,array,linked-list}', '["固定大小 array + hash function（key % size）", "Chaining 處理 collision：每個 bucket 存 list of (key, value) tuples", "Size 選質數（如 1009）讓 mod 分布更均勻", "put/get/remove 都是遍歷 bucket 比對 key"]', 'Average O(1), worst O(n) per op', '["為什麼 size 選質數？— 減少 mod 碰撞，分布更均勻", "什麼是 load factor？— 元素數 / bucket 數，> 0.75 就 resize + rehash", "Chaining vs open addressing？— chaining 串 list，open addressing 找下一個空位"]', '["不能用 Python dict 包一層 — dict 本身就是 hashmap", "get / remove 要處理 key 不存在的 edge case", "遍歷 bucket 比對 key，不是把 key 當 bucket 內的 index"]', '2026-04-16 11:49:22.976844+00', '2026-05-11 07:08:49.4+00', 'Design a HashMap without using any built-in hash table libraries. Support put(key, value), get(key) returning -1 if absent, and remove(key).', 'Input:
["MyHashMap","put","put","get","get","put","get","remove","get"]
[[],[1,1],[2,2],[1],[3],[2,1],[2],[2],[2]]
Output:
[null,null,null,1,-1,null,1,null,-1]', '[]', 2),
	(34, 3, 'Longest Substring Without Repeating Characters', 'medium', '{string,hash-table,sliding-window}', '["Sliding window + HashMap of char → last seen index", "碰到重複時 left = char_index[c] + 1，O(1) 跳轉", "不用清 map — 只覆蓋值，靠 index >= left 判斷是否還在 window", "每步更新 max_len，不要存整串歷史長度"]', 'O(n) time, O(min(n, m)) space where m is charset size', '["為什麼用 dict 不用 set？— dict 存 index 可以 O(1) 跳 left，set 只能一格一格縮", "為什麼條件要 char_index[c] >= left？— 舊 index 可能已在 window 外，忽略它"]', '["空 window 長度是 0，別用 [1] 初始化 max_len — 會整路多 1", "別假設只有 26 個字母 — 題目包含 digits、symbols、spaces", "找到重複時別忘了同時更新該 char 的 index 到 right"]', '2026-04-16 11:56:48.671342+00', '2026-05-11 07:45:56.827+00', 'Given a string s, find the length of the longest substring without repeating characters.', 'Input: s = "abcabcbb"
Output: 3', '[]', 2),
	(35, 8, 'String to Integer (atoi)', 'medium', '{string,math}', '["lstrip 後逐字元用 index 遍歷 — 不要用 split()", "Sign 只看第一個非空白字元，之後 i+=1", "result = result * 10 + int(s[i]) 累加到非 digit 為止", "最後 max(-2**31, min(result, 2**31 - 1)) 一行 clamp"]', 'O(n) time, O(1) space', '["Leading zeros 為什麼不用特別處理？— 0*10+0=0，累加法天然跳過", "為什麼不能用 split()？— split 按空白切成 words，\"-42\" 變成 [\"-42\"] 整塊不是逐字元"]', '["split() 切的是 words 不是 chars — atoi 要逐字元", "Sign 只認一個 — \"+-12\" 要 return 0", "空字串或 lstrip 後為空要 return 0", "記得 clamp，不要讓結果超出 [-2^31, 2^31 - 1]"]', '2026-04-16 11:58:09.049437+00', '2026-05-04 13:59:45.048+00', 'Convert a string to a 32-bit signed integer. Skip leading whitespace, read optional sign, consume digits until non-digit, and clamp to int32 range.', 'Input: s = "   -42"
Output: -42', '[]', 2),
	(32, 383, 'Ransom Note', 'easy', '{hash-table,string,counting}', '["Iterate Counter.items() 不是原字串 — 重複字母才不會重複掃", "Counter[missing_key] 回傳 0 不是 KeyError — 不用先檢查存在性", "Pythonic: Counter(ransomNote) <= Counter(magazine) 就是 multiset subset", "更短: not (Counter(ransomNote) - Counter(magazine))，減法只保留正數", "Early exit: len(ransomNote) > len(magazine) 直接 return False"]', 'O(n+m) time, O(1) space (lowercase English, alphabet bounded by 26)', '["字符集是 Unicode 不是 lowercase？— space 變成 O(k) where k = unique chars", "這 pattern 延伸到哪？— Valid Anagram、Group Anagrams、Minimum Window Substring", "下一題試 Valid Anagram — https://leetcode.com/problems/valid-anagram/"]', '["方向別搞反 — magazine 要能 cover ransomNote，不是反過來"]', '2026-04-16 11:55:44.332059+00', '2026-05-10 09:51:49.313+00', 'Given two strings ransomNote and magazine, return true if ransomNote can be constructed using letters from magazine. Each letter in magazine can only be used once.', 'Input: ransomNote = "aa", magazine = "aab"
Output: true', '["別寫 if letter not in mag_counter — Counter 的 missing key 回傳 0，那行是多餘的", "Loop 的是 note_counter.items() 不是 ransomNote 字串 — 不然 ''aaaaa'' 會重複檢查 ''a'' 五次", "Lowercase-only 題目 space 是 O(1) 不是 O(n) — alphabet 有上限要講清楚"]', 2),
	(30, 128, 'Longest Consecutive Sequence', 'medium', '{array,hash-table,union-find}', '["把 nums 丟進 HashSet，O(1) lookup 是關鍵", "只從「起點」往上數 — num-1 不在 set 才算起點", "從起點跑 while num+1 in set，邊走邊累加 streak", "非起點直接 skip，避免從序列中間重複展開"]', 'O(n) time, O(n) space', '["為什麼總體是 O(n) 而非 O(n²)？— 每個數最多被內層 while 訪問一次，只有起點才觸發展開，攤銷 2n", "如果要回傳序列本身不只是長度？— 記錄起點和長度即可重建"]', '["while 迴圈查的是 set 不是原 list — 查 list 的 in 是 O(n)，會打回 O(n²)", "先判斷 num-1 not in set 再展開，否則每段序列會被算多次", "不需要額外 dict 存每個起點的長度，一個 longest 變數就夠"]', '2026-04-16 11:54:36.268201+00', '2026-05-09 04:16:16.169+00', 'Given an unsorted array of integers, return the length of the longest consecutive elements sequence in O(n) time.', 'Input: nums = [100,4,200,1,3,2]
Output: 4
Explanation: The longest consecutive sequence is [1,2,3,4]', '["外層 for 要 iterate num_set 不是 nums — 有 duplicate 時每個重複起點都會重跑整段序列，退化成 O(n²) TLE"]', 2),
	(36, 394, 'Decode String', 'medium', '{string,stack,recursion}', '["Stack 存 (prev_str, num) — [ 是暫存先不算，] 是現在可以算", "維護 current_str 和 current_num 兩個變數往前掃", "遇到 [ push 然後 reset，遇到 ] pop 出來做 prev + current × num", "數字可能多位：current_num = current_num × 10 + int(ch)", "嵌套天然從內往外解 — LIFO 就是「最內層最先 close」"]', 'O(S) time, O(S) space，S = 輸出長度', '["為什麼不是 O(n)？— 字串複製成本跟輸出長度成正比，不是輸入長度", "能不能用 recursion？— 可以，遇到 [ 遞迴下去解完子字串再回來", "類似 pattern 還有哪些？— Basic Calculator、nested list parsing，嵌套求值都是 stack"]', '["數字要累加不能直接 int(ch) — 輸入可能有 100[a] 這種多位數", "push 之後要記得 reset current_str 和 current_num 為空", "pop 出來是 prev_str + current_str × num，順序別寫反", "像 2[abc]3[cd]ef 裡沒被 bracket 包的 ef 會自然累積到最後的 current_str，不用特別處理"]', '2026-04-16 11:58:47.847011+00', NULL, 'Given an encoded string of form k[encoded_string], return its decoded string. Brackets can be nested and k is a positive integer (may be multi-digit).', 'Input: s = "3[a2[c]]"
Output: "accaccacc"', '[]', 0),
	(59, 215, 'Kth Largest Element in an Array', 'medium', '{array,heap,divide-and-conquer,sorting,quickselect}', '["heapq.nlargest(k, nums)[-1] — 一行解，O(n log k) time O(k) space", "nlargest 內部自己建 size-k min-heap，不需要先 heapify", "最佳解是 quickselect — quicksort 的懶人版，只 recurse 有 target 的那一邊", "Quickselect 平均 O(n)，worst O(n²) 用 random pivot 緩解", "kth largest = (n-k)th smallest in 0-indexed sorted order"]', 'Heap: O(n log k) time, O(k) space. Quickselect: O(n) average, O(n²) worst, O(1) extra space', '["k 接近 n 時怎辦？— 直接 sorted(nums)[-k]，O(n log n) 反而更乾淨", "怎麼避免 quickselect 的 O(n²) worst case？— Random pivot，或 median-of-medians 保證 O(n)", "Streaming 版本（資料一直進來）試試 — https://leetcode.com/problems/kth-largest-element-in-a-stream/"]', '["heapq 是 min-heap，要拿 largest 得用 nlargest 或存負值", "Quickselect 的 partition 要小心 pivot 的最終位置，recurse 時要排除 pivot 本身"]', '2026-04-24 14:25:42.110714+00', '2026-05-10 13:47:51.584+00', 'Given an integer array nums and an integer k, return the kth largest element in the array (kth largest in sorted order, not the kth distinct element).', 'Input: nums = [3,2,1,5,6,4], k = 2
Output: 5', '["別在 nlargest 前面多寫一個 heapify — 完全沒用，還多 O(n) 又 mutate input", "Complexity 分析要對齊實際寫的 code — 上次嘴巴說 O(n log k) 手卻寫了 O(n) 的 heapify，前後不一致", "面試時要主動 walk through trade-off space：sort / heap / quickselect 三種都提，不要只給一個解就停"]', 0),
	(40, 226, 'Invert Binary Tree', 'easy', '{tree,bfs,dfs,recursion}', '["遞迴：root.left, root.right = invert(right), invert(left) 然後 return root", "Tuple swap RHS 整個算完才 assign — 拆兩行會 bug", "迭代版骨架：pop → swap → 推非 None 子節點，三步驟", "queue (deque) = BFS，stack (list) = DFS — 換容器就換遍歷方式", "BFS 用 deque.popleft 才是 O(1)"]', 'O(n) time, O(n) space worst case', '["BFS vs DFS 空間差異？— 平衡樹 DFS 只要 O(log n)，BFS 最後一層就 O(n/2)", "怎麼把 BFS 改成 iterative DFS？— queue 換成 stack，popleft 換成 pop，其他不變", "遞迴 vs 迭代 trade-off？— 遞迴乾淨但 skewed tree 會 stack overflow，迭代可控"]', '["Tuple swap 不能拆成兩行 — 第二行會用到已被覆蓋的 root.right", "別用 list.pop(0) 當 queue — 是 O(n)，整體變 O(n²)", "空間複雜度要連 BFS queue / DFS stack 一起算，不是只有 output"]', '2026-04-16 12:02:10.948175+00', '2026-05-11 07:23:33.287+00', 'Given the root of a binary tree, invert it (mirror left and right at every node) and return the root.', 'Input: root = [4,2,7,1,3,6,9]
Output: [4,7,2,9,6,3,1]', '["每個解法都要附 time / space complexity — 上次 iterative 版漏了，recursive 有寫", "Tuple swap 慣例 left 先 right 後：root.left, root.right = invert(right), invert(left)", "BFS 不會自動比遞迴省空間 — 平衡樹 BFS 是 O(n)，要省空間改 DFS stack"]', 2),
	(41, 98, 'Validate Binary Search Tree', 'medium', '{tree,bst,dfs,bfs,recursion}', '["每個節點帶 (lo, hi) 開區間，整個子樹都要落在區間內", "往左走：hi 收緊成 node.val；往右走：lo 收緊成 node.val", "DFS 把 (lo, hi) 走 args；BFS 塞進 queue tuple", "檢查用嚴格不等式 lo < node.val < hi", "Plan B：BST 的 inorder 遍歷必定嚴格遞增"]', 'O(n) time. DFS space O(h); BFS space O(n) worst case', '["還有什麼解法？— Inorder 遍歷檢查嚴格遞增，BST inorder 必定排序", "為什麼不能只跟 parent 比？— 孫節點可能違反祖父約束，如 [5,1,6,null,null,3,7]", "下一題練 BST inorder — https://leetcode.com/problems/kth-smallest-element-in-a-bst/"]', '["[1,1] 必須回傳 false — 用嚴格 < 不是 <=", "左右子都要同時受 lo 和 hi 兩邊約束，單邊檢查會漏", "Inorder 解法的 prev 要用 nonlocal 或包成 list — 不然 Python 會當成新的 local"]', '2026-04-16 12:02:48.296169+00', '2026-05-08 13:27:31.273+00', 'Given the root of a binary tree, determine if it is a valid BST where every node in the left subtree is strictly less than the node and every node in the right subtree is strictly greater.', 'Input: root = [5,1,6,null,null,3,7]
Output: false', '["更新 (lo, hi) 後要塞回 queue 帶下去 — 不能只在比較時寫對就忘了 enqueue", "BFS 的 space 不是 O(1) 是 O(n) worst case — queue 最寬一層 ~n/2 個 node", "樹題先想 DFS recursion，bounds 當 args 傳；別卡在 BFS 想不出 recursion 結構"]', 2),
	(25, 242, 'Valid Anagram', 'easy', '{hash-table,string,sorting}', '["Counter(s) == Counter(t) 一行解決", "Fixed 26-array 是 O(1) space 但只支援 lowercase a-z", "Counter 用 O(k) space 換來任意 alphabet 支援", "len(s) != len(t) 可早 return 加速"]', 'O(n) time, O(n) space', '["Unicode 怎辦？— Counter 本身就 OK，26-array 解法才壞掉", "café 兩種編碼怎比？— 先 unicodedata.normalize(''NFC'', s) 再丟 Counter", "Group Anagrams 是進階版 — https://leetcode.com/problems/group-anagrams/"]', '["26-array 解的 ord(c) - ord(''a'') 遇到非 ASCII 會 IndexError 或裝錯 bucket", "Counter 數 code points 不是 grapheme — 🇹🇼 (兩個 regional indicator) 會被當兩個字"]', '2026-04-16 11:50:43.510321+00', '2026-04-25 17:15:38.11+00', 'Given two strings s and t, return true if t is an anagram of s. Each character must appear the same number of times in both.', 'Input: s = "anagram", t = "nagaram"
Output: true', '["Counter 解已經 Unicode-safe — follow-up 是給用 26-array 的人問的，不用改 code", "café 在 NFC vs NFD 下可能是 4 或 5 個 code points — 比較前先 normalize"]', 2),
	(42, 102, 'Binary Tree Level Order Traversal', 'medium', '{tree,bfs,breadth-first-search}', '["BFS 骨架：while queue 外層走 level，內層走 current level 的 nodes", "用 for _ in range(len(queue)) 凍結當前層大小，popleft 一次搞定", "drain level 時同步 append node.val 到 level_list — 別先 snapshot 再 drain", "加入 children 前先 check None，別污染 queue", "對稱結構：每次迭代收集當前層，不要把 root 特判在外"]', 'O(n) time, O(n) space — space 上界是最寬那層 (最壞 n/2)，不是樹高', '["Zigzag 版本？— 遍歷順序不變，只在組 level_list 時用 deque.appendleft 或最後 reverse，https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "Bottom-up 版本？— 同骨架，最後 result[::-1] 或 result.reverse()，https://leetcode.com/problems/binary-tree-level-order-traversal-ii/", "遞迴 DFS 版？— helper(node, level)，用 len(levels) == level 判斷該層是否已建立", "BFS vs DFS 空間？— BFS 最壞 O(n/2) 在最後一層，DFS 最壞 O(h) 在 recursion stack"]', '["別把 root 在迴圈外特殊處理 — 會讓邏輯不對稱並需要 if level_list guard", "for node in queue 同時 append 會 invalidate iterator — 要用 for _ in range(size) 配 popleft"]', '2026-04-17 13:03:47.609219+00', '2026-04-24 15:46:37.839+00', 'Given the root of a binary tree, return the level order traversal of its nodes'' values as a list of lists, one sublist per level from top to bottom.', 'Input: root = [3,9,20,null,null,15,7]
Output: [[3],[9,20],[15,7]]', '["又用 list.pop(0) 了 — #226 已經被提醒過是 O(n) 害整體變 O(n²)，下次直接 from collections import deque 配 popleft", "snapshot 層的值時別 walk 兩次 — result.append([n.val for n in queue]) 再 drain 是 double work，drain 時同步收 val 就好", "複雜度別說『O(n) 更精確是 O(2n)』— big O 定義就是丟常數，講『each node O(1) work, total O(n)』才對"]', 2),
	(27, 347, 'Top K Frequent Elements', 'medium', '{array,hash-table,heap,bucket-sort,sorting}', '["三種解法：sorting O(n log n)、min-heap of size k O(n log k)、bucket sort O(n)", "Bucket sort 關鍵：frequency 上限是 len(nums)，所以 frequency 可以當 index", "Min-heap of size k 是 bouncer 演算法 — root 是現任最弱的，新人比他強才換掉", "nlargest 內部就維護 size-k min-heap，input 不需要先 heapify", "Heapify 是 O(n) 不是 O(n log n) — Floyd''s algorithm bottom-up sift down"]', 'Bucket sort O(n); min-heap-of-k O(n log k) time O(k) space; max-heap-of-all O(n + k log n) time O(n) space', '["為什麼找最大 k 個用 min-heap？— root 是當前第 k 大的守門員，新元素比它大才替換", "Min-heap-of-k 真的比 max-heap-of-all 快嗎？— 時間其實常常更慢，贏在 O(k) space 跟 streaming 相容", "下一題試 H-Index — https://leetcode.com/problems/h-index/"]', '["Buckets 長度要 len(nums) + 1，因為 frequency 最大可能等於 len(nums)", "Python heapq 只有 min-heap，要 max-heap 得把 key negate", "Bucket sort 是 O(n) 因為 frequencies 有界 — 一般 sort by 任意 key 沒這個保證"]', '2026-04-16 11:52:17.528054+00', '2026-05-10 13:57:07.779+00', 'Given an integer array nums and an integer k, return the k most frequent elements in any order.', 'Input: nums = [1,1,1,2,2,3], k = 2
Output: [1,2]', '["heapq.nlargest 內部已維護 size-k min-heap — 不要再先 heapify input，那是多餘的 O(n) 工", "Max-heap-of-all 是 O(n + k log n) 不是 O(k log n) — heapify 那個 O(n) 不能省", "Min-heap-of-k 選的真正理由是 O(k) space 跟 streaming — 時間反而常常輸給 max-heap-of-all", "Bucket sort 收齊就 break 並最後 results[:k] — 只用 if len < k 空跑會錯，最後一 bucket 可能把總數推過 k"]', 2),
	(31, 290, 'Word Pattern', 'easy', '{hash-table,string}', '["Bijection 要雙向 check — char→word 和 word→char 兩個 map", "邊 zip 邊 check conflict，不能 build 完再比 length", "用 zip(pattern, words) 取代 range(len(...))，更 Pythonic", "一行精簡版：len(set(zip)) == len(set(pattern)) == len(set(words))", "setdefault(k,v) 可把 conflict check 收一行 — readability 換 cleverness"]', 'O(N) time/space, N = len(s) — string hash 是 O(k)', '["為什麼要先檢查長度？— zip 會截斷到較短的那個，造成 false positive", "為什麼需要雙向 map？— 只做單向會漏掉兩個 char 對到同一個 word 的情況", "下一題試 Isomorphic Strings — https://leetcode.com/problems/isomorphic-strings/"]', '["zip 會 silently truncate — 長度不等時一定要先 return False", "只檢查單向 map 不夠 — pattern=\"ab\", s=\"dog dog\" 會誤判成 true", "set(zip(...)) 技巧依賴長度相等前提，少了 guard 會出 bug"]', '2026-04-16 11:55:05.169277+00', '2026-05-11 07:20:18.597+00', 'Given a pattern and a string s, return true if s follows the same pattern — meaning there is a bijection between letters in pattern and words in s.', 'Input: pattern = "abba", s = "dog cat cat dog"
Output: true', '["Dict comprehension 重複 key 會靜默覆寫 — 要邊 build 邊 check，不能最後比 length", "Space 是 O(N) 不是 O(1) — dict 的 key 是整個 word，不是 char", "String key 的 hash 不是 O(1) — 看 string 長度，整體 time 是 O(N) not O(M)"]', 2),
	(47, 297, 'Serialize and Deserialize Binary Tree', 'hard', '{tree,bfs,design,queue}', '["BFS + null marker (#) — 每個非 null 節點貢獻正好 2 個子 token", "Deserialize：queue 裝已建但未處理子節點的 parent，每 pop 一個就消耗下 2 個 token", "Null 不進 queue、不消耗 token，只佔一個標記位", "用 list 收集 token 再 '',''.join — 迴圈內 string += 是 O(n²)", "每個非 null 父節點恰好消耗 2 個 token 是核心不變量"]', 'O(n) time, O(n) space', '["為什麼需要 null marker？— 不記 null 就無法分辨子節點是父的左還是右", "DFS preorder 行不行？— 可以，遞迴寫更短，但 stack depth 受樹高限制", "complete tree 能省 null marker 嗎？— 可以改用 heap-style indexing (2i+1, 2i+2)"]', '["空樹 edge case — 開頭 if not root: return '''' 比較乾淨，對稱處理 deserialize"]', '2026-04-18 14:39:09.674416+00', NULL, 'Design algorithms to serialize a binary tree to a string and deserialize that string back to the original tree.', 'Input: root = [1,2,3,null,null,null,4]
Output: 1,2,3,#,#,#,4,#,#', '["別再繞 level marker ($1$, $2$) 的路 — 兩棵結構不同的樹可能產出一樣的 level 序列，null marker 才是解結構歧義的正解", "「null 下面還能有 null 跟 value」的樹不存在 — null 沒有子節點，所以 1D 序列的歧義從一開始就不存在", "實作細節三件套：用 deque 不是 list（list 沒 .popleft()）；node.val 要先 str()；null 和 value 兩個分支的分隔符要一致（不然相鄰多個 # 會黏成 ###）"]', 0),
	(49, 153, 'Find Minimum in Rotated Sorted Array', 'medium', '{array,binary-search}', '["Binary search invariant：最小值永遠在 nums[lo..hi]", "比 nums[mid] 跟 nums[hi]，不是跟 nums[lo]", "nums[mid] > nums[hi] → pivot 嚴格在右，lo = mid + 1", "否則最小在左半含 mid，hi = mid（保留 mid）", "迴圈 while lo < hi，結束時 nums[lo] 就是答案"]', 'O(log n) time, O(1) space', '["有重複值怎辦？— LC 154，nums[mid] == nums[hi] 時 hi -= 1，worst case 退化到 O(n)", "找 target 不是 min？— LC 33 要先判斷哪半 sorted 再決定往哪走 — https://leetcode.com/problems/search-in-rotated-sorted-array/", "為什麼比 hi 不比 lo？— 比 lo 在 fully-sorted 時 nums[lo]==nums[mid] 會分不清有沒有 rotate", "找 rotation pivot index？— 同樣邏輯 return lo"]', '["else 分支要包含 mid（hi = mid），不是 hi = mid - 1 — mid 本身可能就是最小", "用 nums[lo] 比較會有 ambiguity：fully-sorted 跟 rotated 在 nums[lo]==nums[mid] 時無法區分"]', '2026-04-19 14:40:54.334314+00', '2026-05-08 15:55:54.367+00', 'Given a sorted array rotated between 1 and n times with unique elements, return the minimum element in O(log n) time.', 'Input: nums = [4,5,6,7,0,1,2]
Output: 0', '["別在 else 分支記 nums[mid+1] 當候選又把 hi 設成 mid - 1 — 會把真正的最小值踢出搜尋範圍，[3,1,2] 會回傳 2", "Dry run 要跑到 lo > hi 為止 — 上次 [2,1] 少跑一輪就下結論，差點以為 return 2", "不要靠 minval 變數補破網 — 選對比較對象（nums[mid] vs nums[hi]）就不需要額外 state，這才是 binary search 的核心技巧", "口頭講 invariant「最小值永遠在 nums[lo..hi]」，不要只說『某半 sorted』 — 後者沒解釋為什麼演算法 correct"]', 2),
	(54, 239, 'Sliding Window Maximum', 'hard', '{array,queue,sliding-window,monotonic-stack,heap}', '["Monotonic deque 存 index，對應 nums 值單調遞減", "新元素進來：從尾部 pop 掉所有比它小的 — 它們又小又舊，永遠沒機會了", "頭部過期就 popleft：dq[0] <= i - k 時移除", "dq[0] 永遠是當前 window 的 max", "Amortized O(n)：每個 index 最多 append 一次、pop 一次"]', 'O(n) time, O(k) space', '["為什麼不用 max-heap？— Peek O(1) 但刪除過期元素 O(k)，或用 lazy deletion 做到 O(n log n) 但不是最優", "為什麼存 index 不是 value？— 要用 index 判斷是否過期（超出 window）", "Amortized 分析怎講？— 看起來 nested loop 像 O(nk)，但每個元素進出 deque 各一次，總操作 O(n)"]', '["Deque 存 index 不是 value — 過期判斷需要 index", "頭部過期檢查用 <= i - k 不是 < i - k — off-by-one 會留下過期元素", "i >= k - 1 才開始 append 到 result — 前 k-1 輪 window 還沒滿"]', '2026-04-21 17:05:28.26906+00', NULL, 'Given an array nums and a window size k, return the max of each sliding window as it moves from left to right across the array.', 'Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]', '["別用 heap 硬解 — nlargest 每輪重建是 O(nk) 會 TLE，要想到 monotonic deque", "寫 dq[0] 前記得先檢查 dq 非空 — 用 if dq and dq[0] <= i - k 的 short-circuit，順序顛倒會 IndexError", "維護 current_max + sec_num 是對的方向但不夠 — 要推廣成『保留所有還有競爭資格的元素』才是 monotonic deque"]', 0),
	(55, 206, 'Reverse Linked List', 'easy', '{linked-list,recursion,two-pointer}', '["Iterative 三 pointer 節奏：save next → flip curr.next = prev → walk prev → walk curr", "next_node 只是書籤：在 curr.next = prev 蓋掉之前先存住下一站", "Recursive base case: head is None or head.next is None — 兩個都要 cover", "Recursive 核心：head.next 同時是『原本下一個』也是『反轉子串列的尾巴』，所以 head.next.next = head 接得上", "new_head 從最深層 base case 一路原封不動傳上來；每層只做收尾一小步"]', 'Iterative O(n) time O(1) space; recursive O(n) time O(n) space (call stack)', '["Ship 哪個？— Iterative，Python 預設 recursion limit ~1000 長 list 會爆 stack", "Recursive 思考框架？— 定義 base case → 信任子問題 → 只做當層多出來那一點點工", "下一題試 LC 92 區間反轉 — https://leetcode.com/problems/reverse-linked-list-ii/"]', '["Iterative: 寫 curr.next = prev 之前一定要先 save next_node，否則 list 後半永久遺失", "Iterative: while 結束時 curr 是 None，要 return prev 不是 curr", "Recursive: head.next.next = head 之後一定要 head.next = None，否則最後兩個 node 形成 cycle"]', '2026-04-22 04:37:04.79955+00', '2026-05-09 08:12:35.447+00', 'Given the head of a singly linked list, reverse the list and return the new head.', 'Input: head = [1,2,3,4,5]
Output: [5,4,3,2,1]', '["卡住時馬上畫 1 → 2 → 3 + prev/curr/next 三個 pointer，zoom in 到當下這個 node，別在腦中追整個 list", "Iterative 別加 if not head: return head — 是 dead code，while 迴圈本身就 handle 空 list", "Recursive 別 thread accumulator helper(head, prev_node) — 是偽 iteration、白賠 O(n) stack；真正遞迴是信任子問題而不是帶狀態往前走"]', 2),
	(33, 20, 'Valid Parentheses', 'easy', '{string,stack}', '["用 stack：遇左括號 push，遇右括號 check top 配不配", "mapping 用 right → left 一個 dict 就夠，不要嵌套", "右括號來時 stack 空 or top 不配 → return False", "掃完檢查 stack 是否為空，不空代表有左括號沒關"]', 'O(n) time, O(n) space', '["為什麼用 stack？— 最近打開的括號必須最先關，LIFO 剛好吻合", "只有一種括號時？— 計數器就夠，不用 stack"]', '["右括號來時 stack 可能是空的，要先檢查才能 peek", "return 直接寫 not stack，不要 True if len==0 else False", "別用嵌套 dict 分 left/right — 一個 right→left mapping 就搞定"]', '2026-04-16 11:56:15.119069+00', '2026-04-22 13:03:25.547+00', 'Given a string containing only the characters ()[]{}, determine if the brackets are properly opened and closed in the correct order.', 'Input: s = "([{}])"
Output: true', '[]', 2),
	(57, 739, 'Daily Temperatures', 'medium', '{array,stack,monotonic-stack}', '["Monotonic non-increasing stack of indices，tail 永遠是目前最冷的待解日", "當前溫度高於 stack 頂時，pop 並寫入 answer[idx] = current_idx - idx", "只存 index 就好，溫度可從 temperatures[idx] 查回來", "迴圈結束後 stack 裡剩下的 index 對應 answer = 0（初始值）"]', 'O(n) time, O(n) space', '["為什麼是 O(n) 不是 O(n²)？— 每個 index 最多被 push 一次 pop 一次，amortized O(1) per element", "如果是 streaming input？— 用 generator 逐步 yield (day_index, days_to_wait)，因為答案會 out-of-order resolve，要帶 index", "嚴格 decreasing 還是 non-increasing？— 條件用 strict >，所以相同溫度不會 pop，stack 是 non-increasing"]', '["pop 條件要 strict >（current > stack top），用 >= 會讓同溫度互相配對出錯", "answer array 先初始化成 0，沒被 pop 到的 index 自動就是正確答案"]', '2026-04-23 14:04:32.003621+00', '2026-05-11 07:09:10.937+00', 'Given an array of daily temperatures, return an array where answer[i] is the number of days until a warmer temperature. If no future day is warmer, answer[i] = 0.', 'Input: temperatures = [73,74,75,71,69,72,76,73]
Output: [1,1,4,2,1,1,0,0]', '["Monotonic stack 不是 monotonic queue — 用 pop()/append() 是 LIFO，註解和口頭都別講錯", "Stack 裡只存 index — 溫度從 temperatures[idx] 查，別再多存 (idx, temp) tuple，連續兩次都犯", "從 i=0 開始、stack 一開始留空 — 別寫 stack=[(0, temps[0])] 配 i=1，空 array 直接 IndexError"]', 2),
	(23, 1, 'Two Sum', 'easy', '{array,hash-table}', '["One-pass HashMap：key 存 complement (target - num)，value 存 index", "每個 num 先查 in hashmap 再寫入 — 避免自己配自己", "找到 match 立刻 return [hashmap[num], i]，不要繼續跑迴圈", "Dict lookup 是 amortized O(1)，最壞 O(n) due to hash collisions"]', 'O(n) time, O(n) space', '["如果 array 已排序？— Two-pointer 從兩端夾，O(n) time O(1) space", "有重複值怎辦？— 先 check 再 insert 就能正確處理 [3,3] target 6", "保證有解嗎？— 題目保證 exactly one solution，所以不用處理 no-match"]', '["回傳的是 indices 不是 values", "先 check complement 再 insert 當前 num — 順序反了會把自己當另一半"]', '2026-04-16 11:45:46.863013+00', '2026-04-22 13:13:02.748+00', 'Given an array of integers nums and a target, return indices of the two numbers that add up to target. Exactly one solution is guaranteed.', 'Input: nums = [2,7,11,15], target = 9
Output: [0,1]', '["找到答案要立刻 return，不要繼續跑完迴圈 — 浪費時間又讓 result 有可能累積多組答案", "不要用 result = [] 累積答案再 return — 一組 pair 直接 return [hashmap[num], i]，乾淨又表達「只會有一組解」", "別說「No corner cases to cover」— 要說「題目保證 exactly one solution 跟 len >= 2，所以不需處理 no-match」展現有想過而非忽略"]', 2),
	(43, 235, 'Lowest Common Ancestor of a Binary Search Tree', 'medium', '{tree,bst,recursion,binary-search}', '["LCA 是第一個 split p 和 q 的節點 — 一個在左子樹，另一個在右子樹（或自己就是 p/q）", "用 BST 性質：root > max(p,q) 往左，root < min(p,q) 往右，否則就是 LCA", "BST 不用 backtrack — iterative 版本 O(1) space，直接 while root 往下走", "node 可以是自己的 ancestor — 若 root.val == p.val 就回傳 root"]', 'O(h) time — O(log n) balanced, O(n) worst case; iterative O(1) space, recursive O(h) stack', '["非 BST 的版本怎麼做？— 失去 ordering，要 post-order recursion 同時往左右找 — https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "為什麼可以 iterative？— BST 每步方向唯一，不需要 call stack 存回溯路徑", "如果 p 或 q 不在樹裡？— 原題保證存在；若不保證要先驗證，否則會回錯節點"]', '["不要假設 p.val < q.val — 用 min/max 或兩邊都判", "判斷條件寫 root.val > max(p,q) 比寫兩個 or 串起來更清楚"]', '2026-04-17 14:19:17.730706+00', '2026-04-23 15:42:43.757+00', 'Given a BST, find the lowest common ancestor (LCA) of two given nodes p and q. A node can be its own ancestor.', 'Input: root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4
Output: 2', '["條件寫得太囉嗦 — p.val <= q.val <= root.val or q.val <= p.val <= root.val 其實就是 root.val >= max(p.val, q.val)，直接用 min/max 讓意圖一目瞭然", "預設寫成 recursive 但沒提 iterative — BST 可以 O(1) space，面試要主動講 trade-off 不要等被問", "edge case 沒口頭走 p 或 q 等於 root 的情況 — 雖然程式正確但要說出來證明有想過"]', 2),
	(44, 200, 'Number of Islands', 'medium', '{array,dfs,bfs,matrix,union-find}', '["雙層 for loop 掃格子，遇到 ''1'' 就觸發 dfs/bfs 並 count += 1", "把走過的 ''1'' 翻成 ''0'' — 當作 visited 標記", "四鄰是 (i±1, j) 跟 (i, j±1) — 不是寫死 0", "BFS 要在 enqueue 時就 mark，避免同一格被塞進 queue 多次", "Python BFS 用 collections.deque 跟 popleft()，pop(0) 是 O(n)"]', 'O(m×n) time, O(m×n) worst-case space', '["不能改 input？— 用 visited set 取代原地翻 ''0''", "大 grid 怕 recursion 爆掉？— 改 iterative BFS 用 deque", "想算最大島面積 — https://leetcode.com/problems/max-area-of-island/"]', '["recursion 在大 grid (如 1000×1000 全 land) 會打爆 Python default recursion limit", "mark-on-dequeue 不會算錯但會浪費 — 同一格可能被鄰居重複 enqueue"]', '2026-04-17 15:51:52.01224+00', '2026-04-23 16:12:23.052+00', 'Given an m×n grid of ''1'' (land) and ''0'' (water), return the number of connected islands. Cells connect 4-directionally.', 'Input: grid =
1 1 0
1 0 0
0 0 1
Output: 2', '["邊界檢查是 w >= 0 跟 z >= 0，不是 > 0 — 上次寫成 > 0 把第 0 row/col 整排漏掉", "DFS → BFS 翻譯時 boundary predicate 容易翻錯，寫完對照一下兩版的 guard 條件", "四鄰座標別寫死 — 要 (i+1,j)(i-1,j)(i,j+1)(i,j-1)，上次把 j 寫成 0 導致無限遞迴", "變數命名對一下 — 上次宣告 count 卻寫 counter += 1，會噴 NameError"]', 3),
	(60, 23, 'Merge k Sorted Lists', 'hard', '{linked-list,heap,divide-and-conquer,merge-sort}', '["Min-heap of list heads：每次 pop 最小，push 它的 next — O(n log k)", "Divide and conquer：pairwise merge，log k 輪 — 一樣 O(n log k)", "Heap push 要加 tiebreaker index：ListNode 本身不可比較", "用 dummy node + tail pointer 串結果，最後回傳 dummy.next"]', 'O(n log k) time, O(k) space (heap) — n = 總節點數, k = list 數', '["為什麼 heap 比 sequential merge 快？— 每個 node 只付 log k 的比較成本，不是 k", "Divide and conquer 的 stack 深度？— O(log k)，比 heap 版更省 heap 空間", "先練 Merge Two Sorted Lists — https://leetcode.com/problems/merge-two-sorted-lists/"]', '["heapq push (val, node) 遇到重複 val 會 crash — 要加 counter/index 當 tiebreaker", "全空的外層 list [None, None, None] 也要能處理，不是只有 lists = []"]', '2026-04-24 15:20:30.407224+00', '2026-05-05 14:31:21.962+00', 'Given an array of k sorted linked lists, merge them into one sorted linked list and return its head.', 'Input: lists = [[1,4,5],[1,3,4],[2,6]]
Output: [1,1,2,3,4,4,5,6]', '["想成 min-stack — 是 min-heap (priority queue)，min-stack 是 O(1) min query 的另一個東西", "mergeTwolists 用 recursion 時 stack depth = O(N) 不是 O(log k) — 長 list 會爆，改 iterative 才安全", "先講 landscape 再選方案：naive O(nk) / heap O(n log k) / D&C O(n log k)，別只丟出一個就停"]', 2),
	(63, 560, 'Subarray Sum Equals K', 'medium', '{array,hash-table,prefix-sum}', '["Prefix sum + HashMap：對每個 prefix_sum 查 prefix_sum - k 在 map 裡幾次", "seen = {0: 1} 初始化 — 讓從頭開始的 subarray 也能配對", "HashMap 存「次數」不是 True/False — 同 prefix_sum 會重複出現", "先 count += seen.get(prefix_sum - k, 0) 再登記自己進 map", "結構跟 Two Sum 一致：查 complement → 登記自己"]', 'O(n) time, O(n) space', '["能用 sliding window 嗎？— 不行，nums 可能有負數，sum 不單調", "如果要回傳起訖 index？— seen 存 index 而非次數，subarray = nums[seen_index+1 : i+1]", "同模式變體 — https://leetcode.com/problems/subarray-sums-divisible-by-k/"]', '["忘記 seen = {0: 1} — 從頭開始、總和剛好 k 的 subarray 會漏掉", "存 True/False 而非 count — 有負數時同 prefix_sum 重複出現會少算", "Brute force sum(nums[i:j]) 是 O(n³) 不是 O(n²) — 每次 sum 又是 O(n)"]', '2026-04-27 14:26:00.496401+00', '2026-05-10 09:42:11.187+00', 'Given an array of integers nums and an integer k, return the total number of contiguous subarrays whose sum equals k.', 'Input: nums = [1,2,3], k = 3
Output: 2', '["sum_counts[x]=2 是兩個合法起點 candidates，不是 double-count — 加進 map 不是加進 count", "Map entry 不會被『用掉』— 同個起點可配多個未來終點，每對都算一個合法 subarray"]', 2),
	(64, 78, 'Subsets', 'medium', '{array,backtracking,bit-manipulation,recursion}', '["每個元素兩個選擇：include 或 exclude → 2^n 個 subset", "Backtracking 骨架：append → recurse → pop（pop 就是 backtrack）", "沒有顯式 base case — path 隨時都是 valid subset，loop 跑完自然 return", "存進 result 要 path[:] 複製，path 是 mutable shared ref", "替代解：iterative result = [[]] 每個 num 翻倍；或 bit mask 0..2^n-1"]', 'O(n * 2^n) time and space — output-sensitive, optimal; aux space O(n) for stack + path', '["為什麼 O(n * 2^n) 是 optimal？— 光是把答案寫出來就有這個 size", "有重複元素怎辦？— 先 sort，同層跳過 duplicate（LC 90） — https://leetcode.com/problems/subsets-ii/", "下一題 Permutations — https://leetcode.com/problems/permutations/"]', '["result.append(path) 會存 reference，全部會一起變 — 一定要 path[:]", "忘了 pop() 的話，下一個 sibling branch 會帶到上一個分支的殘渣"]', '2026-04-27 15:23:06.92052+00', '2026-05-08 13:27:26.679+00', 'Given an array of unique integers nums, return all possible subsets (the power set). The solution set must not contain duplicate subsets.', 'Input: nums = [1,2,3]
Output: [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]', '["別寫 O(2^n) time / O(1) space — path[:] 每次是 O(n) 複製，call stack 深 n 層 → O(n * 2^n) time, O(n) aux", "別想成「pick 0 個、pick 1 個、… pick n 個」分開做 — 每個元素獨立 in/out 的 binary choice tree", "Dry run 卡住時用紙筆畫 indented call tree（縮排 = 深度），別在腦中追；信任 recursive leap"]', 2),
	(62, 155, 'Min Stack', 'medium', '{stack,design}', '["開第二個 mins stack，每次 push 都存 min(val, mins[-1])", "pop 時兩個 stack 一起 pop — 上一個 min 自動 restore", "getMin 直接回傳 mins[-1]，O(1)", "Aux structure 要 mirror access pattern — LIFO 配 parallel stack 不配 heap"]', 'O(1) for all operations, O(n) extra space', '["如何省空間？— mins 只在 val <= mins[-1] 時 push，pop 時相等才一起 pop", "為什麼是 <= 而不是 <？— 重複的最小值要全部記，不然 pop 完 min 會錯，例如 [2,1,1]", "O(1) 額外空間做得到嗎？— 可以，stack 裡存 2*val - oldMin 這種 encoded delta，但犧牲可讀性"]', '["lazy mins stack 在 pop 時要用 == 比對是否同步 pop，別漏掉重複最小值", "別把 self.min 當變數名 — shadow 掉 built-in min() 會在 push 那行爆"]', '2026-04-26 15:46:23.840508+00', '2026-05-09 07:17:53.787+00', 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.', 'Input:
["MinStack","push","push","push","getMin","pop","top","getMin"]
[[],[-2],[0],[-3],[],[],[],[]]
Output:
[null,null,null,null,-3,null,0,-2]', '["別第三次又想用 heap — pop 是 LIFO 拿 top 不是拿 min，arbitrary heap delete 是 O(n)", "卡住時記住：每個位置存『push 當下的 min』，pop 自動 restore 前一個", "top() 是 peek 不是 pop — 別寫成 self.stack.pop()，會把元素吃掉"]', 2),
	(50, 11, 'Container With Most Water', 'medium', '{array,two-pointer,greedy}', '["Two-pointer from兩端夾，width = right - left", "area = min(h_left, h_right) × width", "每次移動較矮那邊 — 較矮是瓶頸，width 只會變小，唯一機會是換更高的 min", "h_left == h_right 時兩邊一起移也對 (但不必特別分支)"]', 'O(n) time, O(1) space', '["為什麼移較矮那邊？— 較高那邊配任何更近的線，min 仍被較矮那邊 cap，width 又變小，不可能贏", "Streaming 一次性讀入能解嗎？— 不行，最壞需 Ω(n) memory；用 monotonic stack 存嚴格遞增的 left-wall candidates，每來一根當 right wall 掃 stack", "下一題試 Trapping Rain Water — https://leetcode.com/problems/trapping-rain-water/"]', '["面積由較矮那邊決定，不是兩邊相加", "width 是 index 差，不是 index+1"]', '2026-04-19 15:39:49.967768+00', '2026-05-05 08:18:42.16+00', 'Given an array of non-negative heights representing vertical lines, find two lines that together with the x-axis form a container holding the most water.', 'Input: height = [1,8,6,2,5,4,8,3,7]
Output: 49', '["cache 了 left_height, right_height 後，算 area 時又寫 height[left], height[right] — 要嘛全用 cache 變數，要嘛別 cache，保持一致", "變數命名 max_amount/amount 太模糊 — 用 max_area/area 直接對應題目語言", "別跳過 brute force O(n²) 直接講最佳解 — 面試官想看你怎麼推導出 two-pointer，不是背答案", "講解時要先說出『為什麼移較矮那邊』的證明，不只描述演算法"]', 2),
	(38, 5, 'Longest Palindromic Substring', 'medium', '{string,dp,two-pointer}', '["Expand around center — 每個 palindrome 都有中心點", "對每個 i 擴兩次：odd (i,i) 和 even (i,i+1)", "從內往外長，不要從外往內 check — 避免重複驗證", "擴展時 s[l]==s[r] 且內部已是 palindrome → 擴後自然是 palindrome"]', 'O(n²) time, O(1) space', '["能不能更快？— Manacher''s Algorithm 是 O(n)，知道存在就好", "為什麼要分 odd 和 even？— 偶數長度 palindrome 中心在兩字元之間，沒有單一中心字元"]', '["別用 recursion 從外往內 check palindrome — 會重複驗證內部", "Python s[l:r+1] slicing 是 O(n)，頻繁 slice 會拉高複雜度", "忘了處理 even length palindrome (e.g. \"bb\") 會漏解"]', '2026-04-16 12:00:47.125334+00', '2026-05-04 13:58:35.739+00', 'Given a string s, return the longest palindromic substring in s.', 'Input: s = "babad"
Output: "bab"
("aba" is also valid)', '[]', 2),
	(51, 15, '3Sum', 'medium', '{array,two-pointer,sorting}', '["先 sort，再 fix i，對 i+1..n-1 做 two-pointer", "s < 0 → left++，s > 0 → right-- (sorted 才能這樣判斷)", "找到三元組後要同時推進 left 和 right，不然會無限迴圈", "三個位置都要去重：i, left, right 各自 skip 相同值", "Optimization: nums[i] > 0 就 break，三個正數不可能和為 0"]', 'O(n²) time, O(1) space (excluding output, ignoring sort stack)', '["為什麼 sort 是關鍵？— 才能用 two-pointer 判斷方向，也讓去重變成比對相鄰元素", "去重為什麼用值比對不是 index？— 題目要 unique triplets 是值層面的，不是位置", "4Sum 怎麼延伸？— 外面再多一層 loop，變 O(n³)"]', '["看似 medium 但細節密度像 hard — sort、三處去重、else 分支要雙指針同移", "i 的去重條件是 i > 0 and nums[i] == nums[i-1]，不是 nums[i] == nums[i+1]"]', '2026-04-20 13:57:20.260058+00', '2026-05-04 07:54:45.096+00', 'Given an integer array nums, return all unique triplets [a, b, c] such that a + b + c = 0. The solution set must not contain duplicate triplets.', 'Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]', '["找到三元組後別忘了 left += 1 和 right -= 1 — 上次漏了導致同一組 triplet 無限被 append", "別用 index_taken set 去重 — duplicate 是值層面的，同一個 index 的數字可以出現在多組 triplet 裡（例如 [-1,0,1] 和 [-1,-1,2] 都用到 -1）", "two-pointer 的 inner loop 要從 i+1 開始不是 i — 否則 num1 自己被當成 num2"]', 2),
	(66, 42, 'Trapping Rain Water', 'hard', '{array,two-pointer,dp,stack}', '["每個 i 的水量 = min(LMAX[i], RMAX[i]) - height[i]", "O(n) space: 兩個 pass 算出 LMAX 跟 RMAX 陣列，再 sum", "O(1) space: two-pointer 從兩端夾，永遠處理較矮那側", "Commit 邏輯: height[l] ≤ height[r] 時 lmax 就是 bottleneck，可以定案前進不用等 true rmax", "Mental model: 站在 i 往左右看最高牆，水位由較矮那面決定"]', 'O(n) time, O(1) space (two-pointer); O(n) time, O(n) space (prefix max)', '["如果是 stream 進來不能回頭？— 改用 monotonic stack", "2D 版本怎麼做？— https://leetcode.com/problems/trapping-rain-water-ii/", "同家族 ''move shorter side'': Container With Most Water — https://leetcode.com/problems/container-with-most-water/"]', '["LMAX/RMAX 要 include i 自己，不然 height[i] 比兩邊高時會算出負數", "暴力 O(n²) 對每個 i 重新掃左右最高 — prefix max 兩個 pass 就夠"]', '2026-05-05 10:21:57.857392+00', '2026-05-07 08:05:07.62+00', 'Given n non-negative integers representing an elevation map where each bar is width 1, compute how much water it can trap after raining.', 'Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6', '["別假設 left pointer 一定能找到更高的右牆 — [3,0,2,0,1] 全域最高在最左邊就會壞掉", "Prefix max 陣列別用 append 反向建 rmax — index 會跟位置脫鉤，要嘛預先配置 [0]*n 直接用 index 寫，要嘛建完 reverse", "Two-pointer 版本 space 是 O(1) 不是 O(n) — code 寫對但 complexity 標錯"]', 2),
	(26, 49, 'Group Anagrams', 'medium', '{array,string,hash-table,sorting}', '["三種 key 三選一：''''.join(sorted(s))、count array tuple、tuple(sorted(Counter.items()))", "最簡寫法：''''.join(sorted(s)) 當 key，O(n·k log k)，任何字元集都通", "最快寫法（限 a-z）：長度 26 的 count array 轉 tuple，O(n·k)", "用 defaultdict(list) 取代 if key in map / else 分支"]', 'O(n·k) with count array, O(n·k log k) with sorted string; O(n·k) space for stored strings', '["tuple vs frozenset 當 key？— tuple hash 較快且 iteration 順序確定，debug 友善", "字母不限 a-z 怎辦？— 改用 tuple(sorted(Counter(s).items()))", "interviewer 想看最簡？— 直接 ''''.join(sorted(s))，可讀性勝過微優化"]', '["dict key 要 immutable — 用 tuple，不能直接塞 list 或 Counter", "str(count)+ch 的編碼在 alphanumeric input 會 collision — ''1''+''1a'' 撞 ''11''+''a''"]', '2026-04-16 11:51:38.318366+00', '2026-05-07 13:54:28.239+00', 'Given an array of strings, group the anagrams together and return the groups in any order.', 'Input: strs = ["eat","tea","tan","ate","nat","bat"]
Output: [["eat","tea","ate"],["tan","nat"],["bat"]]', '["別寫 if not strs: return [[\"\"]] — 主迴圈已正確處理 []（會 return []），這守衛反而 return 錯答案", "空間不是 O(m+n) — 要算進 hashmap 裡 m 個字串，正解是 O(m·n)", "別誤怪 frozenset — 真正的雷是 str(count)+ch 編碼，frozenset(Counter.items()) 本身完全可用", "dry run 的 Output 要寫實際 return 值，不是 hashmap 內容"]', 2),
	(65, 17, 'Letter Combinations of a Phone Number', 'medium', '{hash-table,string,backtracking}', '["想成 DFS over decision tree — 每層一個 digit，每個分支是一個字母選擇，leaf = 一個完整組合", "Base case: len(path) == len(digits) → append path 到 result", "len(path) 本身就是當前 digit 的 index，不用另外帶 start 參數", "path + letter 版本不用 undo；list.append/pop 共享 mutable state 才是真 backtrack"]', 'O(3^a × 4^b × n) time where a+b = len(digits); output O(4^n × n), recursion stack O(n)', '["Empty digits 怎辦？— 開頭擋 if not digits: return []，不然 base case 直接吃到 path='''' 會回傳 ['''']", "如果只要第 k 個組合？— 用 index 數學算 (mixed-radix)，不用枚舉全部", "下一題練 Generate Parentheses — https://leetcode.com/problems/generate-parentheses/"]', '["7 跟 9 是 4 個字母，其他 digit 只有 3 個 — tighter bound 是 3^a × 4^b 不是純 4^n", "path + letter 每次 allocate 新 string — 所以 time 要乘 n，不只是節點數"]', '2026-04-27 16:09:17.659676+00', '2026-05-05 10:49:15.343+00', 'Given a string containing digits 2-9, return all possible letter combinations the number could represent based on a phone keypad mapping.', 'Input: digits = "23"
Output: ["ad","ae","af","bd","be","bf","cd","ce","cf"]', '["別假設 ''always at least one digit'' — 題目允許空字串，要在開頭 return []，否則會錯回傳 ['''']", "別再帶 start 參數 — len(path) 就是當前 index，兩個一起拿是冗餘 state，會多出錯機會", "Complexity 別只寫 O(4^n) — output 每個是長度 n 的 string 要乘 n；recursion stack O(n) 跟 output space O(4^n × n) 要分開講"]', 2),
	(56, 21, 'Merge Two Sorted Lists', 'easy', '{linked-list,recursion}', '["Merge pattern 模板：dummy + tail，while 兩邊都有就接小的 + 推進，迴圈外接剩餘尾巴", "tail = tail.next 抽到 if/else 外面只寫一次，別在兩個分支各寫", "迴圈結束後 tail.next = list1 or list2 — Pythonic 接上剩下那條", "Recursive 寫法：比小的那顆，其 .next = merge(剩下, 另一條)，回傳自己", "兩種寫法都是 O(n+m) time，差別在 space：iterative O(1) vs recursive O(n+m) stack"]', 'O(n+m) time; iterative O(1) space, recursive O(n+m) stack space', '["Production 選哪個？— Iterative dummy 版；Python recursion limit ~1000，長 list 會 stack overflow", "Merge k sorted lists？— Min-heap 取 k 個 head，或 divide-and-conquer 兩兩合併 — https://leetcode.com/problems/merge-k-sorted-lists/", "要不要複製節點？— 不用，splice 原節點，所以 O(1) aux space 才成立"]', '["比較用 <= 而非 < — 相等時保留 list1 在前 stability 較好，講出來加分", "Recursive 兩個分支的參數順序要一致 — 保持 (list1, list2) 的 invariant"]', '2026-04-22 12:00:03.996322+00', '2026-05-05 13:22:26.808+00', 'Given the heads of two sorted linked lists, merge them into one sorted linked list by splicing together their nodes.', 'Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]', '["開頭別寫 if list1 is None: return list2 那組特判 — dummy node 模式天生處理空 input，留著代表沒信任自己的結構", "tail = tail.next 別在 if 和 else 各寫一遍 — 抽到分支外面，重複是 code smell", "Merge pattern 要反射式：dummy → tail → while 接小的推進 → 收尾接 or。還要 scratch head 代表沒內化"]', 2),
	(52, 53, 'Maximum Subarray', 'medium', '{array,dp,divide-and-conquer}', '["Kadane: running_sum = max(x, running_sum + x); best = max(best, running_sum)", "在每個 i 只有兩個選擇：延伸前面那條，或從 x 重開", "重開的時機是 running_sum 已經在 drag 下一個數字下來（running_sum < 0）", "O(n) time, O(1) space — 一邊掃一邊更新 best", "Init 兩種寫法：running_sum=nums[0] best=nums[0]，或 running_sum=0 best=-inf"]', 'O(n) time, O(1) space', '["要回傳 start/end index？— 在『重開』那條分支記下 start 位置", "Max Product Subarray？— 同時 track running max 跟 running min，負乘負會翻身 — https://leetcode.com/problems/maximum-product-subarray/", "Circular array 版？— total - min_subarray vs Kadane max 取大的 — https://leetcode.com/problems/maximum-sum-circular-subarray/"]', '["best 不能 init 成 0 — 全負數會回傳 0，正解應該是最大的那個負數", "subarray 必須 contiguous，不能跳過負數挖洞"]', '2026-04-20 15:26:06.616075+00', '2026-05-07 14:54:45.089+00', 'Given an integer array nums, find the contiguous subarray with the largest sum and return that sum.', 'Input: nums = [-2,1,-3,4,-1,2,1,-5,4]
Output: 6
Explanation: [4,-1,2,1] has the largest sum = 6', '["別用 left-prefix-sum max + right-suffix-sum max 找邊界 — optimal subarray 不一定碰 endpoint，[5,-10,4,-1,4] 答案是中間的 [4,-1,4]=7", "Python 裡 lsum[-1] 是最後一個 element 不是前一個 — 要寫 lsum[i-1] 並 guard i==0", "recurrence 不是『nums[i]<0 就跳過』— 以 i 結尾的 subarray 一定要包含 nums[i]，選擇只在『延伸』還是『從 i 重開』"]', 2),
	(53, 56, 'Merge Intervals', 'medium', '{array,sorting}', '["先按 start 排序 — O(n log n) 不貴，換來「不用回頭」的結構", "Seed result = [intervals[0]]，從 intervals[1:] 開始 for-loop — 省掉每輪 if not result", "判斷條件：current_start <= result[-1][1]（prev_start <= current_start 是排序給的 invariant）", "合併時 result[-1][1] = max(prev_end, current_end) — 延伸與包住兩種 case 都處理掉", "排序後只需跟 result[-1] 比 — result 右端點遞增，跟最後一個不相交就跟全部不相交"]', 'O(n log n) time, O(n) space', '["Streaming 版怎麼做？— SortedList 維持 merged invariant；insert 時 bisect_left 找位置，check predecessor 是否吃到 start，向右 sweep 吞掉所有 start ≤ end 的 intervals；amortized O(log n) per insert（每個 interval 最多被刪一次）。", "為什麼 predecessor 至多一個會 overlap？— Stored intervals 互不相交，兩個 start < s 的 intervals 不可能都 reach 到 s（否則它們自己 overlap，違反 invariant）。", "下一題試 Insert Interval — https://leetcode.com/problems/insert-interval/"]', '["排序給了 prev_start <= current_start 的 invariant — 別再寫 check 浪費條件", "「包住」的 case 不用特判 — max(prev_end, current_end) 自動處理", "空輸入要主動點出有處理 — for-loop 自動 short-circuit 但面試官想聽到"]', '2026-04-20 16:02:44.508739+00', '2026-05-07 14:58:09.086+00', 'Given an array of intervals, merge all overlapping intervals and return the non-overlapping intervals covering all the input.', 'Input: intervals = [[1,3],[2,6],[8,10],[15,18]]
Output: [[1,6],[8,10],[15,18]]', '["Streaming 變體別停在「用 BST 排好再跑同 algo」— 那是 O(n log n) 沒省到。真正的價值是 insert 當下就維持 merged invariant，不是延後 sort。", "bisect_left 是 binary search 找插入點，遇相等回傳 leftmost — predecessor 用 idx-1 取，不是 idx。", "SortedList(key=lambda x: x[0]) 的 bisect_left 要餵 [start] 不是 start — key 函數會對你傳的東西呼叫 x[0]，裸 int 會 TypeError。"]', 2),
	(37, 76, 'Minimum Window Substring', 'hard', '{string,hash-table,sliding-window,two-pointer}', '["認類別：variable window + 多重條件 → 用 formed/required scalar 做 O(1) 驗證", "Skeleton：for r 擴張外層，while valid 收縮內層，答案在內層更新", "兩張表：need (t 的 Counter) + have (當前窗口 count)", "加入時 have[c] == need[c] → formed += 1（剛好達標才加）", "移出時 have[c] < need[c] → formed -= 1（跌破才減，嚴格小於）"]', 'O(m + n) time, O(m + n) space', '["為什麼 O(m) 不是 O(m·n)？— formed scalar 取代每步重掃 need，左右指針各最多走 m 步", "收縮條件用 if 還是 while？— while，要縮到不合法為止才找得到最小窗口", "練同款 formed/required pattern — https://leetcode.com/problems/permutation-in-string/"]', '["收縮時移出的是 s[left] 不是 s[right]", "順序：先判 formed 要不要減 → 再減 have → 再 left += 1", "回傳 slice 是 s[best_l:best_r+1]，別漏 +1"]', '2026-04-16 11:59:41.360437+00', '2026-05-08 07:28:19.693+00', 'Given strings s and t, return the minimum window in s that contains every character of t including duplicates. Return empty string if none exists.', 'Input: s = "ADOBECODEBANC", t = "ABC"
Output: "BANC"', '["別把整數 l 當 dict key — 要 window[s[l]] 不是 window[l]", "回傳要用存下來的 best_l, best_r — loop 結束的 l, r 早就飄走了", "別每步重掃 need.items() 變 O(m·n) — 要用 formed scalar 做 O(1) 檢查", "Dry-run 要 trace 實際程式碼，不是 trace 你以為它在做的事"]', 2),
	(61, 70, 'Climbing Stairs', 'easy', '{dp,math,recursion}', '["Recurrence: f(n) = f(n-1) + f(n-2) — Fibonacci with f(1)=1, f(2)=2", "為什麼不會重複算？— 用『最後一步』分割路徑：1-step 來自 n-1，2-step 來自 n-2，互斥又窮盡", "Memo 標準型：函式頂端 check 一次 → recurse → store → return，不要 call 前各自重複檢查", "Bottom-up 只需保留前兩個值 → O(1) space", "DP 四階段：naive recursion → memoization → tabulation → space-optimized"]', 'O(n) time, O(1) space (optimized); naive recursion O(2^n)', '["Steps {1,2,3}? — f(n)=f(n-1)+f(n-2)+f(n-3), 但 base case 也要更新 f(3)=4 (含 [3] 本身)", "Broken stairs? — 別分段思考，保留 recurrence 但 broken 處 dp[i]=0，零會自然往上傳遞", "下一題 House Robber — https://leetcode.com/problems/house-robber/"]', '["Java/C++ 大 n 會 integer overflow — Fibonacci 成長指數級，n=92 就爆 64-bit", "@lru_cache 直接裝飾 method 會把 self 變成 key — 用 nested helper 或 staticmethod"]', '2026-04-25 08:38:25.811524+00', '2026-05-08 03:49:01.5+00', 'Given n stairs, you can climb 1 or 2 steps at a time. Return the number of distinct ways to reach the top.', 'Input: n = 4
Output: 5', '["Memo cache check 集中在函式頂端做一次,不要 recursive call 前各檢查一次又各寫一次 (重複工)", "DP 變體改 recurrence 也要更新 base case — steps {1,2,3} 時 f(3)=4 不是 3，因為 [3] 自己也算", "Broken stairs 別用『分段』直覺 — 單個壞階可被 2-step 跨過去 (2→4)，要改 base case 而非重組問題；通用心法：先動 state 再動架構"]', 2),
	(39, 104, 'Maximum Depth of Binary Tree', 'easy', '{tree,dfs,bfs,recursion,binary-tree}', '["Recursive DFS：return 1 + max(maxDepth(left), maxDepth(right))", "Base case: node is None → return 0，leaf 自動被涵蓋不用特判", "相信遞迴會給你正確的 subtree 深度 — 只要加 1 就是自己", "BFS 分層：進 while 時先拍 len(queue) 快照，for _ in range(size) 只處理這一層", "另解：queue 存 (node, depth) tuple，免分層直接取 max(depth)"]', 'O(n) time. Space: DFS O(h), BFS O(w) — skewed 樹 BFS 反而 O(1) 贏', '["BFS vs DFS 哪個省 memory？— 看樹形狀：寬樹 DFS 贏 O(log n)，深/skewed 樹 BFS 贏 O(1)", "為什麼 balanced tree BFS 是 O(n)？— 最後一層節點數 ≈ n/2（等比級數：最末項 = 前面總和 + 1）", "Snapshot pattern 還有哪些題？— LC 102 (level order), 199 (right side view), 515 (largest in row)"]', '["max(left, right) 記得 +1 — 別忘了算自己這一層", "Skewed tree 會讓 Python recursion 爆 stack（default limit 1000）", "DFS space = O(h) call stack，BFS space = O(w) queue — 別籠統講 O(n)"]', '2026-04-16 12:01:30.844468+00', '2026-05-08 13:30:18.442+00', 'Given the root of a binary tree, return its maximum depth — the number of nodes along the longest path from root to the farthest leaf.', 'Input: root = [3,9,20,null,null,15,7]
Output: 3', '["看到「level by level」就反射 len(queue) 快照 — 上次卡住想了一下才撈出來", "答之前先講 tradeoffs：DFS 兩行 vs BFS 分層，選一個並說 why — 別直接跳 code", "Dry run 要 trace 每一步 state 變化，別只 dump 最後的值"]', 2),
	(48, 33, 'Search in Rotated Sorted Array', 'medium', '{array,binary-search}', '["One-pass modified binary search — 每輪判斷哪一半是 sorted 的", "nums[lo] <= nums[mid] → 左半 sorted；否則右半 sorted", "看 target 是否落在 sorted 那半的區間 → 決定往哪邊縮", "用 <= 不是 < — lo == mid 時單元素也算 sorted"]', 'O(log n) time, O(1) space', '["為什麼用 <= 不用 <？— lo == mid 時單元素 trivially sorted，[3,1] target 1 用 < 會錯回 -1", "有重複值怎辦？— nums[lo]==nums[mid] 時無法判斷哪半 sorted，lo += 1 退化到 worst O(n)", "下一題練 LC 81 — https://leetcode.com/problems/search-in-rotated-sorted-array-ii/"]', '["target 區間用半開半閉 nums[lo] <= target < nums[mid]，因為 mid 已經 check 過了", "loop 結束直接 return -1 — 別再 check nums[mid]，empty input 時 mid 未定義會 NameError，而且 found 的 case 在 loop 內就 return 了"]', '2026-04-19 13:53:05.84152+00', '2026-05-08 15:58:46.246+00', 'Given a rotated sorted array of distinct integers and a target, return the index of target or -1. Must run in O(log n).', 'Input: nums = [4,5,6,7,0,1,2], target = 0
Output: 4', '["while 條件用 lo <= hi 不是 lo < hi — 否則 lo == hi 那一輪會漏，target 落在最後單元素時會 miss", "別說成 O(n) — binary search 每輪砍半搜索範圍，是 O(log n) time, O(1) space", "duplicates 退化安全論證：要 nums[lo]==nums[mid] 加 nums[mid]!=target 兩個條件，才推得出 nums[lo]!=target — 別跳推論直接從 nums[mid]!=target 推"]', 2),
	(58, 141, 'Linked List Cycle', 'easy', '{linked-list,two-pointer,hash-table}', '["Floyd''s Tortoise and Hare — slow 走 1 步，fast 走 2 步，有 cycle 必相遇", "Canonical 寫法：slow = fast = head，while fast and fast.next 才進 loop", "Hash set 存走過的 node，看到重複就是 cycle", "Set 裝 node 本身即可 — Python __hash__ 預設就是 identity，不用呼叫 id()"]', 'O(n) time, O(1) space (Floyd) or O(n) space (hash set)', '["怎麼做到 O(1) space？— Floyd''s two-pointer，快慢指針在 cycle 裡必會相遇", "為什麼快慢指針一定會相遇？— cycle 裡 fast 每步縮短 1 格距離，最終追上 slow", "找 cycle 起點怎麼做？— 試 LC 142 — https://leetcode.com/problems/linked-list-cycle-ii/"]', '["值可能重複 — 不能用 node.val 判重，要用 node identity (is 不是 ==)", "single node 自己指自己 (node.next = node) 也是 cycle，別漏"]', '2026-04-23 15:35:09.700318+00', '2026-05-09 05:04:19.495+00', 'Given the head of a linked list, determine whether it contains a cycle (some node''s next points back to an earlier node).', 'Input: head = [3,2,0,-4], pos = 1
Output: true', '["起點同步 slow = fast = head — 別錯開成 fast = head.next，會逼出 if fast.next is None 的醜內嵌判斷", "return fast is slow 直接寫就好 — return True if fast is slow else False 是 code smell", "O(n) space 只是第一版 — 面試官一定追問 O(1) space，要馬上接 Floyd"]', 2),
	(45, 207, 'Course Schedule', 'medium', '{graph,bfs,dfs,topological-sort}', '["等價於 directed graph 的 cycle detection — 沒 cycle 就能 topo sort", "[a, b] 建邊方向是 b → a，a 的 in-degree += 1", "Kahn''s: 從 range(numCourses) 找 indegree==0 進 queue (含孤立節點)，pop count+=1，鄰居 -1 歸零再入", "最後 count == numCourses 才是 true；卡住代表有 cycle", "DFS 要用 3-color (WHITE/GRAY/BLACK)，遇到 GRAY 就是 back edge → cycle"]', 'O(V + E) time and space', '["要輸出修課順序？— LC 210，把 count 改成 list，pop 時 append — https://leetcode.com/problems/course-schedule-ii/", "為什麼 DFS 要 3-color 不是 2-color？— 只有 visited/unvisited 會把「已處理完的旁支」誤判成 cycle，GRAY 專門標「還在當前 DFS 路徑上」", "Kahn''s vs DFS 怎麼選？— Kahn''s 邏輯直覺不怕 stack 爆，DFS 寫起來短但 Python 深度大會爆"]', '["箭頭方向別搞反 — [a, b] 是 b → a (b 先修解鎖 a)，不是 a → b", "建 list of lists 用 [[] for _ in range(n)] 不要用 [[]] * n，後者所有 sublist 共享 reference"]', '2026-04-18 13:13:40.584398+00', '2026-05-09 10:57:56.995+00', 'Given numCourses and a list of prerequisite pairs [a, b] meaning b must be taken before a, return true if all courses can be finished.', 'Input: numCourses = 2, prerequisites = [[1,0],[0,1]]
Output: false', '["用 list.pop() 當 queue 其實是 stack 行為 — 要 FIFO 就用 collections.deque + popleft()，不然 LC 210 那種要 topo 順序的題目會錯", "indegree 用 list[0..numCourses-1] 不要 defaultdict — 沒出現在 prerequisites 的孤立課程會漏掉，補 all(dep==0) 只是 hack 治標不治本", "input 把 numCourses 跟 prerequisites 分開給就是暗示 — node universe 是 [0, numCourses) 不是 edges 裡出現過的，讀 constraints 才知道 data structure 怎麼選"]', 2),
	(46, 704, 'Binary Search', 'easy', '{array,binary-search}', '["維持 lo, hi 兩個索引，while lo <= hi 夾擊", "mid = lo + (hi - lo) // 2，比較 nums[mid] 跟 target", "小了 lo = mid + 1，大了 hi = mid - 1，相等就 return", "迴圈結束沒找到就 return -1", "實務上用 bisect.bisect_left，再 check i < len(nums) 且 nums[i] == target"]', 'O(log n) time, O(1) space (iterative)', '["為什麼 lo <= hi 不是 lo < hi？— lo == hi 時還剩一格要檢查，用 < 會漏掉", "找第一個 target（有重複）？— Lower bound：相等不 return，hi = mid（非 mid-1），loop 改 lo < hi", "經典應用是 LIS，O(n log n) 解法靠 bisect_left — https://leetcode.com/problems/longest-increasing-subsequence/"]', '["Python 用 nums[lo:hi+1] 切片會 copy 新 list，O(n) 空間——要用索引比較，不要用 slice", "Java/C++ 寫 (lo+hi)/2 會 integer overflow，要用 lo + (hi-lo)/2；Python int 不溢位但要懂這個 idiom", "bisect 的 key= 套用在 array 元素，search value 本身要已經在 key space，且 array 必須按同一個 key 排序"]', '2026-04-18 14:12:59.017736+00', '2026-05-10 05:21:37.46+00', 'Given a sorted array of integers nums and a target, return the index of target if it exists, otherwise -1.', 'Input: nums = [-1,0,3,5,9,12], target = 9
Output: 4', '["別宣稱 recursive 版本是 O(1) space——遞迴的 call stack 本身就是 O(log n)", "Base case 用索引判斷 lo == hi 就好，不要用 len(nums[lo:hi+1]) == 1——又慢又不 Pythonic", "開頭不用寫 if not nums 跟 len(nums) == 1 的特判——主迴圈的 invariant 會自然處理"]', 2),
	(29, 209, 'Minimum Size Subarray Sum', 'medium', '{array,sliding-window,two-pointer,prefix-sum}', '["全正數 → sliding window O(n) 是最佳解", "for right in range(n) 累加 nums[right]，while sum >= target 就縮 left", "縮 left 前更新 min_length = min(min_length, right - left + 1)", "min_length 初始化成 float(''inf'') 當哨兵，最後沒更新就 return 0", "成立的關鍵：正數 → window sum 對 size 單調 → 縮 left 必減 sum"]', 'O(n) time, O(1) space — left 和 right 各自最多走 n 步', '["如果有負數？— Sliding window 失效，改用 prefix sum + monotonic deque，每個 index 進出 deque 一次仍 O(n)", "O(n log n) 替代解？— Prefix sum + 對每個 i 二分搜最小 j 使 prefix[j] - prefix[i] >= target", "負數版本就是 LC 862 — https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/"]', '["While 條件是 sum >= target 不是 > target", "沒找到要 return 0 不是 -1 或 len(nums)", "Sliding window 成立的前提是「全為正數」— 題目改條件就要換解法"]', '2026-04-16 11:53:51.740543+00', '2026-05-09 14:28:45.317+00', 'Given an array of positive integers and a target, return the minimal length of a contiguous subarray whose sum is >= target, or 0 if none exists.', 'Input: target = 7, nums = [2,3,1,2,4,3]
Output: 2', '["別先 if target > sum(nums): return 0 預掃整個 array — 用 float(''inf'') 哨兵讓主迴圈自己處理就好，省一趟 O(n)", "用 for right in range(n) 配 nums[right]，別寫 range(1, n+1) 再 nums[right-1] — 多繞一層讓讀者要翻譯", "min_length 初始化用 float(''inf'') 不是 n — 用 n 會跟「事先確認有解」的邏輯耦合，拆掉預掃就壞了"]', 2);


--
-- Name: cards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"public"."cards_id_seq"', 66, true);


--
-- PostgreSQL database dump complete
--

-- \unrestrict 6n0tB16XCYaWPkmdk0GPEb6Ni3DABEZC9hqIcrVjCsJGCfwZccvHGKSamU0mtgs

RESET ALL;
